Distributed tensor sharding propagation
mlc-ai/relax pull request #257
Opened 2023-07-01 23:23 UTC by jinhongyii

This PR implements a GSPMD-like sharding spec propagation on Relax DTensor

2023-07-01 23:23 UTC, jinhongyii commented
cc: @tqchen

2023-07-01 23:32 UTC, jinhongyii commented
Things unsupported now: 
1. propagate sharding spec to constant 
2. more high-level relax operator support (Ideally we should use relax operators for mixed dim access patterns, like B[i, j] = f(A[i+j]), and TIR for the rest)

2023-07-02 21:50 UTC, tqchen requested changes

2023-07-02 21:50 UTC, tqchen commented on src/relax/op/tensor/manipulate.cc
> +    .set_attr<FInferStructInfo>("dist.FInferStructInfo",
You can directly register in distributed/manipulate.cc

it is possible to register in different places 

```
TVM_REGISTER_OP("relax.permute_dims")
.set_attr<FInferStructInfo>("dist.FInferStructInfo", distributed::InferDistStructInfoReshape)
```

2023-07-03 00:02 UTC, tqchen approved these changes

2023-07-03 00:02 UTC, merged